// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package xrossover

import "strconv"

type Action byte

const (
	ActionNONE Action = 0
	ActionMove Action = 1
)

var EnumNamesAction = map[Action]string{
	ActionNONE: "NONE",
	ActionMove: "Move",
}

var EnumValuesAction = map[string]Action{
	"NONE": ActionNONE,
	"Move": ActionMove,
}

func (v Action) String() string {
	if s, ok := EnumNamesAction[v]; ok {
		return s
	}
	return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}
