// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package xrossover

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConnectionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConnectionRequest(buf []byte, offset flatbuffers.UOffsetT) *ConnectionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConnectionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishConnectionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConnectionRequest(buf []byte, offset flatbuffers.UOffsetT) *ConnectionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConnectionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConnectionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConnectionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConnectionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConnectionRequest) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConnectionRequest) Udpaddr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConnectionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConnectionRequestAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(username), 0)
}
func ConnectionRequestAddUdpaddr(builder *flatbuffers.Builder, udpaddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(udpaddr), 0)
}
func ConnectionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
