// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package xrossover

import "strconv"

type Payload byte

const (
	PayloadNONE              Payload = 0
	PayloadConnectionRequest Payload = 1
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:              "NONE",
	PayloadConnectionRequest: "ConnectionRequest",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":              PayloadNONE,
	"ConnectionRequest": PayloadConnectionRequest,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
