// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package xrossover

import "strconv"

type Payload byte

const (
	PayloadNONE              Payload = 0
	PayloadConnectionRequest Payload = 1
	PayloadObjectRegistry    Payload = 2
	PayloadPlayerBox         Payload = 3
	PayloadBall              Payload = 4
	PayloadPlayerInput       Payload = 5
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:              "NONE",
	PayloadConnectionRequest: "ConnectionRequest",
	PayloadObjectRegistry:    "ObjectRegistry",
	PayloadPlayerBox:         "PlayerBox",
	PayloadBall:              "Ball",
	PayloadPlayerInput:       "PlayerInput",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":              PayloadNONE,
	"ConnectionRequest": PayloadConnectionRequest,
	"ObjectRegistry":    PayloadObjectRegistry,
	"PlayerBox":         PayloadPlayerBox,
	"Ball":              PayloadBall,
	"PlayerInput":       PayloadPlayerInput,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
